Repository Anything-Minecraft-Team/anything-minecraft, pull requests merged in 2021-01, with the labels that each got.

#30 Added contributing guidelines
  CONTRIBUTING.md
Labels: documentation

#28 Added running server in the background
  README.md
  info/en_us/server jars.md
  tutorials/en_us/Setting up your minecraft server.md
Labels: enhancement

#20 Codeowners and Pull request template
  .github/CODEOWNERS
  .github/pull_request_template.md
Labels: enhancement

#33 Fixed some formatting
  info/en_us/server jars.md
Labels: bug

#27 Overhauling Anything Minecraft
  CONTRIBUTORS.md
  README.md
  info/en_us/SERVER_JARS.md
  info/en_us/USEFUL_PLUGINS.md
Labels: documentation, enhancement

#45 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation
